In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]

In [3]:
my_list

[1, 2, 3]

In [4]:
type(my_list)

list

In [8]:
my_array = np.array(my_list)

In [9]:
type(my_array)

numpy.ndarray

In [13]:
my_list_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
my_arr_mat = np.array(my_list_mat)

In [15]:
my_arr_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [18]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [22]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
np.linspace(0, 3, 20)

array([0.        , 0.15789474, 0.31578947, 0.47368421, 0.63157895,
       0.78947368, 0.94736842, 1.10526316, 1.26315789, 1.42105263,
       1.57894737, 1.73684211, 1.89473684, 2.05263158, 2.21052632,
       2.36842105, 2.52631579, 2.68421053, 2.84210526, 3.        ])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# random from 0 to 1
np.random.rand(10)

array([0.32072824, 0.63966878, 0.63289707, 0.44681167, 0.83394077,
       0.54390339, 0.16574073, 0.71589718, 0.70233246, 0.95128084])

In [31]:
# random from 0 to 1
np.random.rand(3, 3)

array([[0.13471617, 0.59394806, 0.02802461],
       [0.6075473 , 0.15354603, 0.19113345],
       [0.62826928, 0.068211  , 0.83668358]])

In [35]:
np.random.randn(2)

array([0.17215548, 0.69741917])

In [36]:
np.random.randn(2, 2)

array([[ 1.19909886,  2.30833749],
       [-0.90907572, -1.80664628]])

In [37]:
np.random.randint(0, 10)

3

In [38]:
np.random.randint(0, 10, 3)

array([8, 2, 5])

In [59]:
arr_1 = np.arange(30)

In [60]:
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [61]:
ran_arr = np.random.randint(1, 61, 10)

In [62]:
ran_arr

array([27,  3, 46, 11, 55, 22, 34, 50, 14, 47])

In [75]:
arr_1 = arr_1.reshape(6, 5)

In [76]:
ran_arr.max()

55

In [77]:
ran_arr.min()

3

In [78]:
ran_arr.argmax()

4

In [79]:
ran_arr.argmin()

1

In [80]:
arr_1.shape

(6, 5)

In [81]:
arr_1.dtype

dtype('int64')

In [2]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
list(range(1, 11))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]