In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[8]

8

In [5]:
arr[1:6]

array([1, 2, 3, 4, 5])

In [6]:
arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr[:3]

array([0, 1, 2])

In [9]:
arr[2:5] = 20

In [10]:
arr

array([ 0,  1, 20, 20, 20,  5,  6,  7,  8,  9])

In [35]:
arr = np.arange(0, 10)

In [36]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
slice_of_arr = arr[0: 5]

In [38]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [39]:
slice_of_arr[:] = 20

In [40]:
slice_of_arr

array([20, 20, 20, 20, 20])

In [41]:
arr

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9])

In [42]:
arr_copy = arr.copy()

In [43]:
arr_copy

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9])

In [44]:
arr_copy[:] = 30

In [45]:
arr_copy

array([30, 30, 30, 30, 30, 30, 30, 30, 30, 30])

In [46]:
arr

array([20, 20, 20, 20, 20,  5,  6,  7,  8,  9])

In [48]:
arr_2d = np.array([[10, 20, 30], [40, 50, 60], [100, 200, 300]])

In [49]:
arr_2d

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [100, 200, 300]])

In [55]:
arr_2d[2][1]

200

In [58]:
arr_2d[2, 0]

100

In [62]:
arr_2d[:2,1:]

array([[20, 30],
       [50, 60]])

In [64]:
arr_2d[1:3,:]

array([[ 40,  50,  60],
       [100, 200, 300]])

In [65]:
arr = np.arange(0, 10)

In [67]:
bool_arr = arr > 3

In [68]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [69]:
arr[bool_arr]

array([4, 5, 6, 7, 8, 9])

In [72]:
arr[arr > 5]

array([6, 7, 8, 9])

In [74]:
arr2d = np.arange(0, 50).reshape(5,10)

In [75]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [77]:
arr2d[2:4, 1:5]

array([[21, 22, 23, 24],
       [31, 32, 33, 34]])

In [78]:
arr2d[1:3, 3:5]

array([[13, 14],
       [23, 24]])